/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class UniswapFactory extends Contract {
  functions: {
    getExchange(token: string): Promise<string>;

    getToken(exchange: string): Promise<string>;

    getTokenWithId(token_id: number | string | BigNumber): Promise<string>;

    initializeFactory(
      template: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    createExchange(
      token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    exchangeTemplate(): Promise<string>;
    tokenCount(): Promise<BigNumber>;
  };
  filters: {
    NewExchange(token: string | null, exchange: string | null): EventFilter;
  };
}
